### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SwethaChukka**
...

### CODE REVIEW

**Comment by SwethaChukka** [comment]
SQL2
[S30_Assignment.docx](https://github.com/super30admin/Sql1/files/13327099/S30_Assignment.docx)

**Comment by SwethaChukka** [comment]
[SQL2.docx](https://github.com/super30admin/Sql1/files/13329242/SQL2.docx)

**Comment by SwethaChukka** [comment]
SQL2

**Comment by Rohan-Balakrishna** [comment]
Good Work !

**Comment by Rohan-Balakrishna** [comment]
Good Work !

**Pull request closed without merging**
